name: Build Flutter APK

on:
  push:
    branches: [ main ] # Triggers the build whenever you push to main
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug # Debug build bypasses strict Keystore signing

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload APK Artifact
        id: upload-step # <-- Crucial ID tag to extract the output URL
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Display Clickable Link
        run: |
          echo "### 📱 Download Your Build Directly" >> $GITHUB_STEP_SUMMARY
          echo "Click here to download your compiled app: [Download Mobile APK](${{ steps.upload-step.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY

