name: Build Flutter APK

on:
  push:
    branches: [ main ] # Triggers the build whenever you push to main
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug # Debug build bypasses strict Keystore signing

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-debug.apk


      - name: Upload APK Artifact
        id: upload-step
        uses: actions/upload-artifact@v4
        with:
          name: voxray_pro-apk
          path: build/app/outputs/**/*.apk  # <-- Captures the APK regardless of the exact subfolder


      - name: Display Clickable Link
        run: |
          echo "### 📱 Download Your Build Directly" >> $GITHUB_STEP_SUMMARY
          echo "Click here to download your compiled app: [Download Mobile APK](${{ steps.upload-step.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY

      - name: Send APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ 8828121077 }}
          token: ${{ 8997391510:AAG6Cq1tat_nbPJ_5VBx6VNW-455KuaAVX4 }}
          message: "New dev build ready!"
          document: build/app/outputs/flutter-apk/app-debug.apk # Update path to your raw APK


