name: Clean Old Workflow Runs
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 14 # Keeps runs from the last 14 days
          keep_minimum_runs: 3 # Always ensures the last 3 runs are saved
